# Generated by Django 5.2.8 on 2026-06-16 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0002_match_bracket"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="added_money",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8, null=True
            ),
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.PositiveIntegerField()),
                (
                    "payout_type",
                    models.CharField(
                        choices=[("flat", "Flat Rate"), ("percentage", "Percentage")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ["place"],
                "unique_together": {("tournament", "place")},
            },
        ),
    ]
